import styles from "./ListItem2.module.scss";
import Ingredient from "../Ingredient/Ingredient";
import ProductListContext from "../ProductList/ProductListContext";

const ListItem2 = (props) => {
  return (
    <ProductListContext.Consumer>
      {(context) => (
        <div>
          <li>
            <h3 className={styles.product__params_title}>{props.titleForm}</h3>
            {props.id == "pizza" ? (
              <div>
                <Ingredient
                  ingredient={context.ingredient1}
                  productCost2={props.productCost2}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  titleForm={props.titleForm}
                  id={props.id}
                  showImg={props.showImg}
                />
                <Ingredient
                  ingredient={context.ingredient2}
                  productCost2={props.productCost2}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  titleForm={props.titleForm}
                  id={props.id}
                  showImg={props.showImg}
                />
                <Ingredient
                  ingredient={context.ingredient3}
                  productCost2={props.productCost2}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  id={props.id}
                  showImg={props.showImg}
                  titleForm={props.titleForm}
                />
                <Ingredient
                  ingredient={context.ingredient4}
                  productCost2={props.productCost2}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  id={props.id}
                  showImg={props.showImg}
                  titleForm={props.titleForm}
                />
                <Ingredient
                  ingredient={context.ingredient5}
                  productCost2={props.productCost2}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  id={props.id}
                  showImg={props.showImg}
                  titleForm={props.titleForm}
                />
                <Ingredient
                  ingredient={context.ingredient6}
                  productCost2={props.productCost2}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  id={props.id}
                  showImg={props.showImg}
                  titleForm={props.titleForm}
                />
              </div>
            ) : props.id == "salad" ? (
              <div>
                <Ingredient
                  ingredient={context.ingredient1}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  id={props.id}
                  showImg={props.showImg}
                  titleForm={props.titleForm}
                />
                <Ingredient
                  ingredient={context.ingredient2}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  id={props.id}
                  showImg={props.showImg}
                  titleForm={props.titleForm}
                />
                <Ingredient
                  ingredient={context.ingredient3}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  id={props.id}
                  showImg={props.showImg}
                  titleForm={props.titleForm}
                />
                <Ingredient
                  ingredient={context.ingredient4}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  id={props.id}
                  showImg={props.showImg}
                  titleForm={props.titleForm}
                />
                <Ingredient
                  ingredient={context.ingredient5}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  id={props.id}
                  showImg={props.showImg}
                  titleForm={props.titleForm}
                />
                <Ingredient
                  ingredient={context.ingredient6}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  id={props.id}
                  showImg={props.showImg}
                  titleForm={props.titleForm}
                />
                <Ingredient
                  ingredient={context.ingredient7}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  id={props.id}
                  showImg={props.showImg}
                  titleForm={props.titleForm}
                />
              </div>
            ) : (
              <div>
                <Ingredient
                  ingredient={context.ingredient1}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  id={props.id}
                  showImg={props.showImg}
                  titleForm={props.titleForm}
                />
                <Ingredient
                  ingredient={context.ingredient2}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  id={props.id}
                  showImg={props.showImg}
                  titleForm={props.titleForm}
                />
                <Ingredient
                  ingredient={context.ingredient3}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  id={props.id}
                  showImg={props.showImg}
                  titleForm={props.titleForm}
                />
                <Ingredient
                  ingredient={context.ingredient4}
                  addCashToTotalPrice={props.addCashToTotalPrice}
                  addCashToTotalPrice2={props.addCashToTotalPrice2}
                  id={props.id}
                  showImg={props.showImg}
                  titleForm={props.titleForm}
                />
              </div>
            )}
          </li>
        </div>
      )}
    </ProductListContext.Consumer>
  );
};

export default ListItem2;
